server:
  port: 8001

mybatis:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mapper/*.xml                      #mapper映射文件路径

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: jojiang86
    dbcp2:
      min-idle: 5                         #数据库连接池维持最小连接数
      initial-size: 5                     #初始化连接数连接数
      max-total: 5                        #最大连接数
      max-wait-millis: 200                #等待连接获取的最大超时时间